INSERT INTO USERS (username) VALUES ('ABC');
INSERT INTO USERS (username) VALUES ('DEF');
INSERT INTO USERS (username) VALUES ('GHI');
INSERT INTO USERS (username) VALUES ('JKL');

INSERT INTO MESSAGES (message) VALUES ('AKHAKAHKHAKHAAHKAHAKHAHA');
INSERT INTO MESSAGES (message) VALUES ('DADDASDADSDSDSDSDSDSDDDDSDS');
INSERT INTO MESSAGES (message) VALUES ('wewewewewewwwww');
INSERT INTO MESSAGES (message) VALUES ('Jgfhfhfhfhfhfhfh');