CREATE TABLE USERS (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    username VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE MESSAGES (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    message VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);